[versions]
backdrop = "1.0.0"
capsule = "2.1.1"
compileSdk = "35"
core = "3.5.1"
fat = "1.4.4"
koinAndroidxCompose = "3.5.6"
minSdk = "25"
accompanistSystemuicontroller = "0.36.0"
agp = "8.13.1"
androidxJunit = "1.3.0"
coilCompose = "2.1.0"
czxing = "1.1.0"
datastorePreferences = "1.1.7"
espressoCoreVersion = "3.7.0"
kotlin = "2.2.21"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
kotlinReflect = "2.0.21"
kotlinxCoroutinesAndroid = "1.8.1"
kotlinxCoroutinesCore = "1.8.1"
lifecycleRuntimeKtx = "2.9.2"
activityCompose = "1.10.1"
composeBom = "2024.11.00"
material = "1.12.0"
material3 = "1.3.2"
multidex = "2.0.1"
navigationCompose = "2.4.0"
okio = "3.14.0"
sunmidockSdk = "1.0.3"
sunmiprotocolsdk = "1.0.0"
workRuntimeKtx = "2.10.3"
composeMaterial3 = "1.5.5"
appcompat = "1.7.1"
constraintlayout = "2.1.4"
okhttp = "4.10.0"
adapterRxjava2 = "2.9.0"
gson = "2.13.1"
printerx = "1.0.18"
objectbox = "4.3.0"
koinAndroid = "3.5.6"
zip4j = "2.11.5"
sunmiEcr="2.0.22"
jetbrainsKotlinJvm = "2.0.21"
foundation = "1.9.0"
greendao = "3.3.0"
greendaoGradlePlugin = "3.3.1"
runtime = "1.9.0"
uiToolingPreview = "1.9.0"
uiTooling = "1.9.0"
constraintlayoutCompose ="1.1.1"
camerax_version = "1.4.2"
lottieCompose = "6.3.0"
billing = "1.1.0"
[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistSystemuicontroller" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanistSystemuicontroller" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-datastore-preferences-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "datastorePreferences" }
androidx-espresso-core-v330 = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
androidx-junit-v112 = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
backdrop = { module = "io.github.kyant0:backdrop", version.ref = "backdrop" }
capsule = { module = "io.github.kyant0:capsule", version.ref = "capsule" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
core = { module = "com.google.zxing:core", version.ref = "core" }
czxing = { module = "io.github.devilsen:czxing", version.ref = "czxing" }
fat = { module = "com.github.aasitnikov:fat-aar-android", version.ref = "fat" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koinAndroidxCompose" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlinReflect" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
material = { module = "com.google.android.material:material", version.ref = "material" }
material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-compose-material3 = { group = "androidx.wear.compose", name = "compose-material3", version.ref = "composeMaterial3" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
okhttp3 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
logginginterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "adapterRxjava2" }
adapter-rxjava2 = { module = "com.squareup.retrofit2:adapter-rxjava2", version.ref = "adapterRxjava2" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "adapterRxjava2" }
printerx = { module = "com.sunmi:printerx", version.ref = "printerx" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinAndroid" }
sunmi-ecr-service={group = "com.sunmi",name="sunmi-ecr-service",version.ref="sunmiEcr"}
sunmidock-sdk = { module = "com.sunmi:SunmiDock-SDK", version.ref = "sunmidockSdk" }
sunmiprotocolsdk = { module = "com.sunmi:SunmiProtocolSDK", version.ref = "sunmiprotocolsdk" }
zip4j = { module = "net.lingala.zip4j:zip4j", version.ref = "zip4j" }
greendao = { module = "org.greenrobot:greendao", version.ref = "greendao" }
greendao-gradle-plugin = { module = "org.greenrobot:greendao-gradle-plugin", version.ref = "greendaoGradlePlugin" }
androidx-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "runtime" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "uiToolingPreview" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "uiTooling" }
constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayoutCompose" }

camerax-core = { module = "androidx.camera:camera-core",version.ref="camerax_version"}
camerax-lifecycle = { module = "androidx.camera:camera-lifecycle",version.ref="camerax_version"}
camerax-camera2 = { module = "androidx.camera:camera-camera2",version.ref="camerax_version"}
camerax-view  = { module = "androidx.camera:camera-view",version.ref="camerax_version"}
androidx-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottieCompose" }
billing = { group = "com.google.androidbrowserhelper", name = "billing", version.ref = "billing" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
